name: iOS CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "ios-sample/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "ios-sample/**"

jobs:
  build:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: ios-sample

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          xcodebuild -version

      - name: Build iOS app
        run: |
          xcodebuild -project BridgeSample.xcodeproj \
            -workspace YourApp.xcworkspace \
            -scheme BridgeSample \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            clean build
